config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  
  resources :payments
  resources :documents
  resources :units
  resources :phones
  resources :users
  resources :payment_methods
  resources :expenses
  resources :phone_suppliers
  resources :suppliers
  resources :supplier_types
  resources :document_types
  resources :months
  resources :years
  resources :motives
  resources :fees
  resources :roles
  resources :addresses
  resources :cities
  resources :regions
  resources :communes
  resources :zip_codes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/commune.rb
class Commune < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :document_type
  belongs_to :expense
  belongs_to :supplier
end

app/models/document_type.rb
class DocumentType < ApplicationRecord
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :motive
  belongs_to :month
  belongs_to :year
end

app/models/fee.rb
class Fee < ApplicationRecord
end

app/models/month.rb
class Month < ApplicationRecord
end

app/models/motive.rb
class Motive < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :payment_method
  belongs_to :user
  belongs_to :motive
  belongs_to :month
  belongs_to :year
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :supplier_type
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :user
  belongs_to :address
  belongs_to :commune
  belongs_to :city
  belongs_to :region
  belongs_to :zip_code
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  belongs_to :fee
end

app/models/year.rb
class Year < ApplicationRecord
end

app/models/zip_code.rb
class ZipCode < ApplicationRecord
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]

  # GET /documents or /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:folio, :document_type_id, :expense_id, :supplier_id)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :folio %>
    <%= form.text_field :folio %>
  </div>

  <div class="field">
    <%= form.label :document_type_id %>
    <%= form.text_field :document_type_id %>
  </div>

  <div class="field">
    <%= form.label :expense_id %>
    <%= form.text_field :expense_id %>
  </div>

  <div class="field">
    <%= form.label :supplier_id %>
    <%= form.text_field :supplier_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>Folio</th>
      <th>Document type</th>
      <th>Expense</th>
      <th>Supplier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.folio %></td>
        <td><%= document.document_type_id %></td>
        <td><%= document.expense_id %></td>
        <td><%= document.supplier_id %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Folio:</strong>
  <%= @document.folio %>
</p>

<p>
  <strong>Document type:</strong>
  <%= @document.document_type_id %>
</p>

<p>
  <strong>Expense:</strong>
  <%= @document.expense_id %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @document.supplier_id %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>