config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  
  resources :payments
  resources :documents
  resources :units
  resources :phones
  resources :users
  resources :payment_methods
  resources :expenses
  resources :phone_suppliers
  resources :suppliers
  resources :supplier_types
  resources :document_types
  resources :months
  resources :years
  resources :motives
  resources :fees
  resources :roles
  resources :addresses
  resources :cities
  resources :regions
  resources :communes
  resources :zip_codes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/commune.rb
class Commune < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :document_type
  belongs_to :expense
  belongs_to :supplier
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :motive
  belongs_to :month
  belongs_to :year
end

app/models/fee.rb
class Fee < ApplicationRecord
end

app/models/month.rb
class Month < ApplicationRecord
end

app/models/motive.rb
class Motive < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :payment_method
  belongs_to :user
  belongs_to :motive
  belongs_to :month
  belongs_to :year
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :supplier_type
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :user
  belongs_to :address
  belongs_to :commune
  belongs_to :city
  belongs_to :region
  belongs_to :zip_code
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  belongs_to :fee
end

app/models/year.rb
class Year < ApplicationRecord
end

app/models/zip_code.rb
class ZipCode < ApplicationRecord
end

app/controllers/motives_controller.rb
class MotivesController < ApplicationController
  before_action :set_motive, only: %i[ show edit update destroy ]

  # GET /motives or /motives.json
  def index
    @motives = Motive.all
  end

  # GET /motives/1 or /motives/1.json
  def show
  end

  # GET /motives/new
  def new
    @motive = Motive.new
  end

  # GET /motives/1/edit
  def edit
  end

  # POST /motives or /motives.json
  def create
    @motive = Motive.new(motive_params)

    respond_to do |format|
      if @motive.save
        format.html { redirect_to @motive, notice: "Motive was successfully created." }
        format.json { render :show, status: :created, location: @motive }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @motive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motives/1 or /motives/1.json
  def update
    respond_to do |format|
      if @motive.update(motive_params)
        format.html { redirect_to @motive, notice: "Motive was successfully updated." }
        format.json { render :show, status: :ok, location: @motive }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @motive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motives/1 or /motives/1.json
  def destroy
    @motive.destroy
    respond_to do |format|
      format.html { redirect_to motives_url, notice: "Motive was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motive
      @motive = Motive.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def motive_params
      params.require(:motive).permit(:motivo)
    end
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/motives_helper.rb
module MotivesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/motives/_form.html.erb
<%= form_with(model: motive) do |form| %>
  <% if motive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(motive.errors.count, "error") %> prohibited this motive from being saved:</h2>

      <ul>
        <% motive.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :motivo %>
    <%= form.text_field :motivo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/motives/edit.html.erb
<h1>Editing Motive</h1>

<%= render 'form', motive: @motive %>

<%= link_to 'Show', @motive %> |
<%= link_to 'Back', motives_path %>

app/views/motives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Motives</h1>

<table>
  <thead>
    <tr>
      <th>Motivo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @motives.each do |motive| %>
      <tr>
        <td><%= motive.motivo %></td>
        <td><%= link_to 'Show', motive %></td>
        <td><%= link_to 'Edit', edit_motive_path(motive) %></td>
        <td><%= link_to 'Destroy', motive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Motive', new_motive_path %>

app/views/motives/new.html.erb
<h1>New Motive</h1>

<%= render 'form', motive: @motive %>

<%= link_to 'Back', motives_path %>

app/views/motives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Motivo:</strong>
  <%= @motive.motivo %>
</p>

<%= link_to 'Edit', edit_motive_path(@motive) %> |
<%= link_to 'Back', motives_path %>