config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  
  resources :payments
  resources :documents
  resources :units
  resources :phones
  resources :users
  resources :payment_methods
  resources :expenses
  resources :phone_suppliers
  resources :suppliers
  resources :supplier_types
  resources :document_types
  resources :months
  resources :years
  resources :motives
  resources :fees
  resources :roles
  resources :addresses
  resources :cities
  resources :regions
  resources :communes
  resources :zip_codes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/commune.rb
class Commune < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :document_type
  belongs_to :expense
  belongs_to :supplier
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :motive
  belongs_to :month
  belongs_to :year
end

app/models/fee.rb
class Fee < ApplicationRecord
end

app/models/month.rb
class Month < ApplicationRecord
end

app/models/motive.rb
class Motive < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :payment_method
  belongs_to :user
  belongs_to :motive
  belongs_to :month
  belongs_to :year
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :supplier_type
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :user
  belongs_to :address
  belongs_to :commune
  belongs_to :city
  belongs_to :region
  belongs_to :zip_code
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  belongs_to :fee
end

app/models/year.rb
class Year < ApplicationRecord
end

app/models/zip_code.rb
class ZipCode < ApplicationRecord
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: %i[ show edit update destroy ]

  # GET /units or /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1 or /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units or /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: "Unit was successfully created." }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1 or /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: "Unit was successfully updated." }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1 or /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: "Unit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unit_params
      params.require(:unit).permit(:tipo, :user_id, :address_id, :commune_id, :city_id, :region_id, :zip_code_id)
    end
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/units/_form.html.erb
<%= form_with(model: unit) do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
        <% unit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :address_id %>
    <%= form.text_field :address_id %>
  </div>

  <div class="field">
    <%= form.label :commune_id %>
    <%= form.text_field :commune_id %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.text_field :city_id %>
  </div>

  <div class="field">
    <%= form.label :region_id %>
    <%= form.text_field :region_id %>
  </div>

  <div class="field">
    <%= form.label :zip_code_id %>
    <%= form.text_field :zip_code_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Units</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>User</th>
      <th>Address</th>
      <th>Commune</th>
      <th>City</th>
      <th>Region</th>
      <th>Zip code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.tipo %></td>
        <td><%= unit.user_id %></td>
        <td><%= unit.address_id %></td>
        <td><%= unit.commune_id %></td>
        <td><%= unit.city_id %></td>
        <td><%= unit.region_id %></td>
        <td><%= unit.zip_code_id %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @unit.tipo %>
</p>

<p>
  <strong>User:</strong>
  <%= @unit.user_id %>
</p>

<p>
  <strong>Address:</strong>
  <%= @unit.address_id %>
</p>

<p>
  <strong>Commune:</strong>
  <%= @unit.commune_id %>
</p>

<p>
  <strong>City:</strong>
  <%= @unit.city_id %>
</p>

<p>
  <strong>Region:</strong>
  <%= @unit.region_id %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @unit.zip_code_id %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>