config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  
  resources :payments
  resources :documents
  resources :units
  resources :phones
  resources :users
  resources :payment_methods
  resources :expenses
  resources :phone_suppliers
  resources :suppliers
  resources :supplier_types
  resources :document_types
  resources :months
  resources :years
  resources :motives
  resources :fees
  resources :roles
  resources :addresses
  resources :cities
  resources :regions
  resources :communes
  resources :zip_codes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/commune.rb
class Commune < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :document_type
  belongs_to :expense
  belongs_to :supplier
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :motive
  belongs_to :month
  belongs_to :year
end

app/models/fee.rb
class Fee < ApplicationRecord
end

app/models/month.rb
class Month < ApplicationRecord
end

app/models/motive.rb
class Motive < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :payment_method
  belongs_to :user
  belongs_to :motive
  belongs_to :month
  belongs_to :year
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :supplier_type
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :user
  belongs_to :address
  belongs_to :commune
  belongs_to :city
  belongs_to :region
  belongs_to :zip_code
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  belongs_to :fee
end

app/models/year.rb
class Year < ApplicationRecord
end

app/models/zip_code.rb
class ZipCode < ApplicationRecord
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  before_action :set_fee, only: %i[ show edit update destroy ]

  # GET /fees or /fees.json
  def index
    @fees = Fee.all
  end

  # GET /fees/1 or /fees/1.json
  def show
  end

  # GET /fees/new
  def new
    @fee = Fee.new
  end

  # GET /fees/1/edit
  def edit
  end

  # POST /fees or /fees.json
  def create
    @fee = Fee.new(fee_params)

    respond_to do |format|
      if @fee.save
        format.html { redirect_to @fee, notice: "Fee was successfully created." }
        format.json { render :show, status: :created, location: @fee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fees/1 or /fees/1.json
  def update
    respond_to do |format|
      if @fee.update(fee_params)
        format.html { redirect_to @fee, notice: "Fee was successfully updated." }
        format.json { render :show, status: :ok, location: @fee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fees/1 or /fees/1.json
  def destroy
    @fee.destroy
    respond_to do |format|
      format.html { redirect_to fees_url, notice: "Fee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fee
      @fee = Fee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fee_params
      params.require(:fee).permit(:cuota)
    end
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/fees/_form.html.erb
<%= form_with(model: fee) do |form| %>
  <% if fee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fee.errors.count, "error") %> prohibited this fee from being saved:</h2>

      <ul>
        <% fee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cuota %>
    <%= form.number_field :cuota %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fees/edit.html.erb
<h1>Editing Fee</h1>

<%= render 'form', fee: @fee %>

<%= link_to 'Show', @fee %> |
<%= link_to 'Back', fees_path %>

app/views/fees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fees</h1>

<table>
  <thead>
    <tr>
      <th>Cuota</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fees.each do |fee| %>
      <tr>
        <td><%= fee.cuota %></td>
        <td><%= link_to 'Show', fee %></td>
        <td><%= link_to 'Edit', edit_fee_path(fee) %></td>
        <td><%= link_to 'Destroy', fee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fee', new_fee_path %>

app/views/fees/new.html.erb
<h1>New Fee</h1>

<%= render 'form', fee: @fee %>

<%= link_to 'Back', fees_path %>

app/views/fees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cuota:</strong>
  <%= @fee.cuota %>
</p>

<%= link_to 'Edit', edit_fee_path(@fee) %> |
<%= link_to 'Back', fees_path %>